services:
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      DOMAIN: ${DOMAIN}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - internal
    volumes:
      - ./nginx/production/templates:/etc/nginx/templates/
      - ./public/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - nodejs
  
  nodejs:
    container_name: "nodejs"
    restart: unless-stopped
    image: "nodejs"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROD_MODE: "true"
      DOMAIN: ${DOMAIN}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      AUTODELETE_TIME: ${AUTODELETE_TIME}
      PLAUSIBLE_DOMAIN: ${PLAUSIBLE_DOMAIN}
      PRIVACY_POLICY: ${PRIVACY_POLICY}
      IMGUR_KEY: ${IMGUR_KEY}
    networks:
      - internal

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path /var/www/certbot/ --email ${EMAIL} -d ${DOMAIN} --agree-tos --no-redirect  --non-interactive

networks:
  internal:
    driver: bridge
